"""Local MCP wrapper for the public GeochemistryPi CLI."""

from .cli_driver import CliDriverError, CliInteractionDriver, CliProcessError, CliRunCancelledError, CliRunResult, PromptTimeoutError, UnexpectedPromptError, UnusedResponsesError, WorkspacePathError
from .constants import SERVER_VERSION as __version__
from .interaction_plan import (
    AnalysisPlanCompiler,
    AnomalyDetectionPlanCompiler,
    ClassificationPlanCompiler,
    ClusteringPlanCompiler,
    DecompositionPlanCompiler,
    InteractionPlan,
    InteractionStep,
    PlanCompilationError,
    RegressionPlanCompiler,
    TimeSeriesPlanCompiler,
)
from .schemas import (
    AnalysisRequest,
    AllModelsSelection,
    AnomalyDetectionRequest,
    BuiltInDatasetReference,
    ClassificationRequest,
    ClusteringRequest,
    CompatibilityPolicy,
    DecompositionRequest,
    DesktopDatasetReference,
    ExplicitDatasetReference,
    IsolationForestAnomalyDetectionSettings,
    KMeansClusteringSettings,
    LinearRegressionSettings,
    LocalOutlierFactorAnomalyDetectionSettings,
    LogisticRegressionSettings,
    PCADecompositionSettings,
    RegressionRequest,
    ResourceLimits,
    ScalingMethod,
    SingleModelSelection,
    TimeSeriesRequest,
)

__all__ = [
    "AnalysisPlanCompiler",
    "AnalysisRequest",
    "AllModelsSelection",
    "AnomalyDetectionPlanCompiler",
    "AnomalyDetectionRequest",
    "BuiltInDatasetReference",
    "ClassificationPlanCompiler",
    "ClassificationRequest",
    "ClusteringPlanCompiler",
    "ClusteringRequest",
    "CompatibilityPolicy",
    "DecompositionPlanCompiler",
    "DecompositionRequest",
    "DesktopDatasetReference",
    "ExplicitDatasetReference",
    "CliDriverError",
    "CliInteractionDriver",
    "CliProcessError",
    "CliRunCancelledError",
    "CliRunResult",
    "InteractionPlan",
    "InteractionStep",
    "IsolationForestAnomalyDetectionSettings",
    "KMeansClusteringSettings",
    "LogisticRegressionSettings",
    "LinearRegressionSettings",
    "LocalOutlierFactorAnomalyDetectionSettings",
    "PlanCompilationError",
    "PCADecompositionSettings",
    "PromptTimeoutError",
    "RegressionPlanCompiler",
    "RegressionRequest",
    "ResourceLimits",
    "ScalingMethod",
    "SingleModelSelection",
    "TimeSeriesPlanCompiler",
    "TimeSeriesRequest",
    "UnexpectedPromptError",
    "UnusedResponsesError",
    "WorkspacePathError",
    "__version__",
]
